export const jobs = [
  {
    id: 1,
    company: "Amazon",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/de/Amazon_icon.png",
    posted: "5 Days ago",
    title: "Senior UI/UX Designer",
    type: "Part Time",
    level: "Senior Level",
    salary: "$120/hr",
    location: "Mumbai, India",
  },
  {
    id: 2,
    company: "Google",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    posted: "2 Days ago",
    title: "Frontend Engineer",
    type: "Full Time",
    level: "Mid Level",
    salary: "$90/hr",
    location: "Bangalore, India",
  },
  {
    id: 3,
    company: "Microsoft",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    posted: "1 Week ago",
    title: "React Developer",
    type: "Remote",
    level: "Senior Level",
    salary: "$110/hr",
    location: "Hyderabad, India",
  },
  {
    id: 4,
    company: "Netflix",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    posted: "3 Days ago",
    title: "Product Designer",
    type: "Contract",
    level: "Senior Level",
    salary: "$130/hr",
    location: "Remote",
  },
  {
    id: 5,
    company: "Meta",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Meta-Logo.png",
    posted: "6 Days ago",
    title: "UI Engineer",
    type: "Full Time",
    level: "Mid Level",
    salary: "$100/hr",
    location: "Gurgaon, India",
  },
  {
    id: 6,
    company: "Adobe",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Adobe_Corporate_Logo.png",
    posted: "4 Days ago",
    title: "UX Researcher",
    type: "Part Time",
    level: "Senior Level",
    salary: "$95/hr",
    location: "Noida, India",
  },
  {
    id: 7,
    company: "Flipkart",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/13/Flipkart_logo.png",
    posted: "1 Day ago",
    title: "Frontend Intern",
    type: "Internship",
    level: "Entry Level",
    salary: "$20/hr",
    location: "Bangalore, India",
  },
  {
    id: 8,
    company: "Swiggy",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/13/Swiggy_logo.png",
    posted: "2 Weeks ago",
    title: "UI Designer",
    type: "Full Time",
    level: "Junior Level",
    salary: "$70/hr",
    location: "Remote",
  },
  {
    id: 9,
    company: "Zomato",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/75/Zomato_logo.png",
    posted: "3 Days ago",
    title: "Product Engineer",
    type: "Full Time",
    level: "Mid Level",
    salary: "$85/hr",
    location: "Delhi, India",
  },
  {
    id: 10,
    company: "Paytm",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Paytm_Logo.png",
    posted: "1 Week ago",
    title: "Frontend Developer",
    type: "Remote",
    level: "Mid Level",
    salary: "$75/hr",
    location: "Remote",
  },
];
